blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Have a question or idea?
    url: https://github.com/pranavagarkar07/taskvault-lite/discussions
    about: Start a discussion instead of an issue.
